"""init migration

Revision ID: c92f22adb195
Revises: 49b897717079
Create Date: 2016-03-07 11:36:38.114000

"""

# revision identifiers, used by Alembic.
revision = 'c92f22adb195'
down_revision = '49b897717079'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
